In [1]:
import numpy as np
from pylab import *
import random
import sklearn
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split as tts
from sklearn import preprocessing as pr
from scipy import stats as st
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import linear_model
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

def adjusted_r2(R2,sample_size,independent_variables):
    n = sample_size
    p = independent_variables
    return (1-(1-R2)*(n-1)/(n-p-1))

data = pd.read_csv('data.csv')
data.head()

sex  height    FA     P     F  age    district  race
0    0   174.5  28.9  19.3  26.4   21     colombo     1
1    0   170.1  28.8  17.8  24.3   20  kurunagala     1
2    0   166.6  28.8  18.1  25.1   21  rathnapura     1
3    0   165.5  28.5  19.2  25.7   21     colombo     1
4    0   177.0  30.0  19.8  27.0   20       galle     1

In [2]:
data = data[(data['race']==1)&(data['F']<70)]
df = data[['F','FA','P','sex','height']]

In [3]:
df.head()

F    FA     P  sex  height
0  26.4  28.9  19.3    0   174.5
1  24.3  28.8  17.8    0   170.1
2  25.1  28.8  18.1    0   166.6
3  25.7  28.5  19.2    0   165.5
4  27.0  30.0  19.8    0   177.0

In [4]:
X = df[['P','sex']].values.reshape(-1,2)
y = df['height'].values.reshape(-1,1)

X_train, X_test, y_train, y_test = tts(X, y, test_size=0.20, random_state=42)
sample_size = len(X_train)
independent_variables = 1
#training the model
model = linear_model.LinearRegression(normalize=True)
model.fit(X_train, y_train)
fit = model.predict(X_train)
print(model.coef_,model.intercept_)

#plt.scatter(X.values.reshape(-1,1), y.values.reshape(-1,1))
#plt.plot(X.values.reshape(-1,1), fit, c='r')
#plt.show()
r2 = sklearn.metrics.r2_score(y_train, fit)
r2 = adjusted_r2(r2,sample_size,independent_variables)
print("Train Adj. R2 = ",r2)

#Test model
fit = model.predict(X_test)
r2 = sklearn.metrics.r2_score(y_test, fit)
r2 = adjusted_r2(r2,sample_size,independent_variables)
print("Test Adj. R2 = ",r2)

[[ 4.77441787 -4.96993196]] [80.69228876]
Train Adj. R2 =  0.7372883556727376
Test Adj. R2 =  0.8106873125307333


In [5]:
X = df[['F','sex']].values.reshape(-1,2)
y = df['height'].values.reshape(-1,1)

X_train, X_test, y_train, y_test = tts(X, y, test_size=0.20, random_state=42)
sample_size = len(X_train)
independent_variables = 1
#training the model
model = linear_model.LinearRegression(normalize=True)
model.fit(X_train, y_train)
fit = model.predict(X_train)
print(model.coef_,model.intercept_)

#plt.scatter(X.values.reshape(-1,1), y.values.reshape(-1,1))
#plt.plot(X.values.reshape(-1,1), fit, c='r')
#plt.show()
r2 = sklearn.metrics.r2_score(y_train, fit)
r2 = adjusted_r2(r2,sample_size,independent_variables)
print("Train Adj. R2 = ",r2)

#Test model
fit = model.predict(X_test)
r2 = sklearn.metrics.r2_score(y_test, fit)
r2 = adjusted_r2(r2,sample_size,independent_variables)
print("Test Adj. R2 = ",r2)

[[ 3.47275309 -5.00889024]] [80.70553712]
Train Adj. R2 =  0.7587096143501101
Test Adj. R2 =  0.8484332638669886


In [6]:
X = df[['FA','sex']].values.reshape(-1,2)
y = df['height'].values.reshape(-1,1)

X_train, X_test, y_train, y_test = tts(X, y, test_size=0.20, random_state=42)
sample_size = len(X_train)
independent_variables = 1
#training the model
model = linear_model.LinearRegression(normalize=True)
model.fit(X_train, y_train)
fit = model.predict(X_train)
print(model.coef_,model.intercept_)

#plt.scatter(X.values.reshape(-1,1), y.values.reshape(-1,1))
#plt.plot(X.values.reshape(-1,1), fit, c='r')
#plt.show()
r2 = sklearn.metrics.r2_score(y_train, fit)
r2 = adjusted_r2(r2,sample_size,independent_variables)
print("Train Adj. R2 = ",r2)

#Test model
fit = model.predict(X_test)
r2 = sklearn.metrics.r2_score(y_test, fit)
r2 = adjusted_r2(r2,sample_size,independent_variables)
print("Test Adj. R2 = ",r2)

[[ 3.7140036  -3.22654808]] [63.74928738]
Train Adj. R2 =  0.8435844613068719
Test Adj. R2 =  0.9014537090239106


In [7]:
X = df[['P','F','sex']].values.reshape(-1,3)
y = df['height'].values.reshape(-1,1)

X_train, X_test, y_train, y_test = tts(X, y, test_size=0.20, random_state=42)
sample_size = len(X_train)
independent_variables = 1
#training the model
model = linear_model.LinearRegression(normalize=True)
model.fit(X_train, y_train)
fit = model.predict(X_train)
print(model.coef_,model.intercept_)

#plt.scatter(X.values.reshape(-1,1), y.values.reshape(-1,1))
#plt.plot(X.values.reshape(-1,1), fit, c='r')
#plt.show()
r2 = sklearn.metrics.r2_score(y_train, fit)
r2 = adjusted_r2(r2,sample_size,independent_variables)
print("Train Adj. R2 = ",r2)

#Test model
fit = model.predict(X_test)
r2 = sklearn.metrics.r2_score(y_test, fit)
r2 = adjusted_r2(r2,sample_size,independent_variables)
print("Test Adj. R2 = ",r2)

[[ 2.22590574  2.24958988 -4.17434463]] [70.6641665]
Train Adj. R2 =  0.7780828940886176
Test Adj. R2 =  0.8617637900398917


In [8]:
X = df[['P','FA','sex']].values.reshape(-1,3)
y = df['height'].values.reshape(-1,1)

X_train, X_test, y_train, y_test = tts(X, y, test_size=0.20, random_state=42)
sample_size = len(X_train)
independent_variables = 1
#training the model
model = linear_model.LinearRegression(normalize=True)
model.fit(X_train, y_train)
fit = model.predict(X_train)
print(model.coef_,model.intercept_)

#plt.scatter(X.values.reshape(-1,1), y.values.reshape(-1,1))
#plt.plot(X.values.reshape(-1,1), fit, c='r')
#plt.show()
r2 = sklearn.metrics.r2_score(y_train, fit)
r2 = adjusted_r2(r2,sample_size,independent_variables)
print("Train Adj. R2 = ",r2)

#Test model
fit = model.predict(X_test)
r2 = sklearn.metrics.r2_score(y_test, fit)
r2 = adjusted_r2(r2,sample_size,independent_variables)
print("Test Adj. R2 = ",r2)

[[ 1.19596096  3.14642999 -2.78968829]] [57.73904631]
Train Adj. R2 =  0.8504038832094913
Test Adj. R2 =  0.9090921495715686


In [9]:
X = df[['F','FA','sex']].values.reshape(-1,3)
y = df['height'].values.reshape(-1,1)

X_train, X_test, y_train, y_test = tts(X, y, test_size=0.20, random_state=42)
sample_size = len(X_train)
independent_variables = 1
#training the model
model = linear_model.LinearRegression(normalize=True)
model.fit(X_train, y_train)
fit = model.predict(X_train)
print(model.coef_,model.intercept_)

#plt.scatter(X.values.reshape(-1,1), y.values.reshape(-1,1))
#plt.plot(X.values.reshape(-1,1), fit, c='r')
#plt.show()
r2 = sklearn.metrics.r2_score(y_train, fit)
r2 = adjusted_r2(r2,sample_size,independent_variables)
print("Train Adj. R2 = ",r2)

#Test model
fit = model.predict(X_test)
r2 = sklearn.metrics.r2_score(y_test, fit)
r2 = adjusted_r2(r2,sample_size,independent_variables)
print("Test Adj. R2 = ",r2)

[[ 1.18477785  2.91364453 -2.71069519]] [56.34097392]
Train Adj. R2 =  0.8576594852749311
Test Adj. R2 =  0.9209244403149642


In [10]:
X = df[['P','F','FA','sex']].values.reshape(-1,4)
y = df['height'].values.reshape(-1,1)

X_train, X_test, y_train, y_test = tts(X, y, test_size=0.20, random_state=42)
sample_size = len(X_train)
independent_variables = 1
#training the model
model = linear_model.LinearRegression(normalize=True)
model.fit(X_train, y_train)
fit = model.predict(X_train)
print(model.coef_,model.intercept_)

#plt.scatter(X.values.reshape(-1,1), y.values.reshape(-1,1))
#plt.plot(X.values.reshape(-1,1), fit, c='r')
#plt.show()
r2 = sklearn.metrics.r2_score(y_train, fit)
r2 = adjusted_r2(r2,sample_size,independent_variables)
print("Train Adj. R2 = ",r2)

#Test model
fit = model.predict(X_test)
r2 = sklearn.metrics.r2_score(y_test, fit)
r2 = adjusted_r2(r2,sample_size,independent_variables)
print("Test Adj. R2 = ",r2)

[[ 0.36694024  1.04657074  2.8328675  -2.63683496]] [55.36113152]
Train Adj. R2 =  0.8581099100763118
Test Adj. R2 =  0.9211168127687865


In [11]:
#for sex = 0
male = df.query("sex == 0")

X = male[['P','F','FA']].values.reshape(-1,3)
y = male['height'].values.reshape(-1,1)

X_train, X_test, y_train, y_test = tts(X, y, test_size=0.20, random_state=42)
sample_size = len(X_train)
independent_variables = 1
#training the model
model = linear_model.LinearRegression(normalize=True)
model.fit(X_train, y_train)
fit = model.predict(X_train)
print(model.coef_,model.intercept_)

#plt.scatter(X.values.reshape(-1,1), y.values.reshape(-1,1))
#plt.plot(X.values.reshape(-1,1), fit, c='r')
#plt.show()
r2 = sklearn.metrics.r2_score(y_train, fit)
r2 = adjusted_r2(r2,sample_size,independent_variables)
print("Train Adj. R2 = ",r2)

#Test model
fit = model.predict(X_test)
r2 = sklearn.metrics.r2_score(y_test, fit)
r2 = adjusted_r2(r2,sample_size,independent_variables)
print("Test Adj. R2 = ",r2)

[[-0.14782822  1.29628183  3.36656811]] [43.83681192]
Train Adj. R2 =  0.8205693828159941
Test Adj. R2 =  0.4497557312160094


In [12]:
#for sex = 1
male = df.query("sex == 1")

X = male[['P','F','FA']].values.reshape(-1,3)
y = male['height'].values.reshape(-1,1)

X_train, X_test, y_train, y_test = tts(X, y, test_size=0.20, random_state=42)
sample_size = len(X_train)
independent_variables = 1
#training the model
model = linear_model.LinearRegression(normalize=True)
model.fit(X_train, y_train)
fit = model.predict(X_train)
print(model.coef_,model.intercept_)

#plt.scatter(X.values.reshape(-1,1), y.values.reshape(-1,1))
#plt.plot(X.values.reshape(-1,1), fit, c='r')
#plt.show()
r2 = sklearn.metrics.r2_score(y_train, fit)
r2 = adjusted_r2(r2,sample_size,independent_variables)
print("Train Adj. R2 = ",r2)

#Test model
fit = model.predict(X_test)
r2 = sklearn.metrics.r2_score(y_test, fit)
r2 = adjusted_r2(r2,sample_size,independent_variables)
print("Test Adj. R2 = ",r2)

[[0.47820068 1.6578331  1.86012163]] [61.53623327]
Train Adj. R2 =  0.6123493270632945
Test Adj. R2 =  0.7999271420378881


### Follwoing is given by a forward selection model, but may need to consider scaling of variabels due to different units

In [13]:
X = df[['F','FA','sex']].values.reshape(-1,3)
y = df['height'].values.reshape(-1,1)

X_train, X_test, y_train, y_test = tts(X, y, test_size=0.20,random_state=42)
sample_size = len(X_train)
independent_variables = 1
#training the model
model = linear_model.LinearRegression(normalize=True)
model.fit(X_train, y_train)
fit = model.predict(X_train)
print(model.coef_,model.intercept_)

#plt.scatter(X.values.reshape(-1,1), y.values.reshape(-1,1))
#plt.plot(X.values.reshape(-1,1), fit, c='r')
#plt.show()
r2 = sklearn.metrics.r2_score(y_train, fit)
r2 = adjusted_r2(r2,sample_size,independent_variables)
print("Train Adj. R2 = ",r2)

#Test model
fit = model.predict(X_test)
r2 = sklearn.metrics.r2_score(y_test, fit)
r2 = adjusted_r2(r2,sample_size,independent_variables)
print("Test Adj. R2 = ",r2)

[[ 1.18477785  2.91364453 -2.71069519]] [56.34097392]
Train Adj. R2 =  0.8576594852749311
Test Adj. R2 =  0.9209244403149642
